### ISSUE TITLE
Killing a busy worker puts task on failed

### ISSUE THREAD

**Issue by villasv** [villasv/turbine#65]
This is something that can be problematic during a scale in. If we're very unlucky to have one of the worker machines running a task and it's chosen to be terminated (instead of an entirely idle machine), the task will fail.

How often this scenario conflicts with the usual scenario of workers dying? Workers are usually not meant to die in the middle of a task, so it makes sense to reschedule them. Tasks are already meant to be `up_for_retry`ed anyway.

**Comment by villasv** [comment]
Relevant celery broker transport options:
[`task-acks-late`](http://docs.celeryproject.org/en/latest/userguide/configuration.html#task-acks-late)
[`task-reject-on-worker-lost`](http://docs.celeryproject.org/en/latest/userguide/configuration.html#task-reject-on-worker-lost)

**Comment by villasv** [comment]
Welp, transport options are not read from the environment. Gotta wait until `airflow==1.10.2`.

**Comment by villasv** [comment]
We might consider using [instance protection](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-instance-termination.html#instance-protection) to make each worker protect itself from scaling down if it's under load.

This may work against low-load scaling-in, because if all workers are active but very light on load they'll all refuse to die. It's probably best to make auto-scaling have the authority to kill busy workers and just be sure that those will get restarted.

If restarting tasks would hurt SLAs, the scaling timeout should be increased - like it used to be when scaling in could only happen in response to empty queues.

**Comment by villasv** [comment]
Another possibility is to use [lifecycle hooks](https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html#lifecycle-hooks-overview) to prepare the worker to die gracefully. If we could make it stop ingesting messages from the queue and prolong the `Terminating` state untill all tasks are finished, we would solve the scaling in problem once and for all. Not even retries would be required.

**Comment by villasv** [comment]
http://docs.celeryproject.org/en/latest/userguide/workers.html

Shutdown should be accomplished using the TERM signal.

When shutdown is initiated the worker will finish all currently executing tasks before it actually terminates. If these tasks are important, you should wait for it to finish before doing anything drastic, like sending the KILL signal.

**Comment by villasv** [comment]
Gotta reproduce the problem, investigate the signal that was captured and reevaluate if Celery configs are enough to mitigate the problem.

**Comment by villasv** [comment]
```
*** Reading local file: /efs/logs/my_dag/runme_3/2018-12-31T00:02:00+00:00/2.log
[2019-01-01 22:41:49,748] {models.py:1361} INFO - Dependencies all met for <TaskInstance: my_dag.runme_3 2018-12-31T00:02:00+00:00 [failed]>
[2019-01-01 22:41:49,753] {models.py:1361} INFO - Dependencies all met for <TaskInstance: my_dag.runme_3 2018-12-31T00:02:00+00:00 [failed]>
[2019-01-01 22:41:49,753] {models.py:1573} INFO - 
--------------------------------------------------------------------------------
Starting attempt 2 of 1
--------------------------------------------------------------------------------

[2019-01-01 22:41:49,772] {models.py:1595} INFO - Executing <Task(BashOperator): runme_3> on 2018-12-31T00:02:00+00:00
[2019-01-01 22:41:49,773] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run my_dag runme_3 2018-12-31T00:02:00+00:00 --job_id 2050 --raw -sd DAGS_FOLDER/my_dag.py --cfg_path /tmp/tmp94g_vgjb']
[2019-01-01 22:41:50,116] {base_task_runner.py:101} INFO - Job 2050: Subtask runme_3 [2019-01-01 22:41:50,116] {settings.py:174} INFO - setting.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800
[2019-01-01 22:41:50,396] {base_task_runner.py:101} INFO - Job 2050: Subtask runme_3 [2019-01-01 22:41:50,396] {__init__.py:51} INFO - Using executor CeleryExecutor
[2019-01-01 22:41:50,500] {base_task_runner.py:101} INFO - Job 2050: Subtask runme_3 [2019-01-01 22:41:50,500] {models.py:271} INFO - Filling up the DagBag from /airflow/dags/my_dag.py
[2019-01-01 22:41:50,625] {base_task_runner.py:101} INFO - Job 2050: Subtask runme_3 [2019-01-01 22:41:50,625] {cli.py:484} INFO - Running <TaskInstance: my_dag.runme_3 2018-12-31T00:02:00+00:00 [running]> on host ip-10-0-0-97.ec2.internal
[2019-01-01 22:41:50,686] {bash_operator.py:74} INFO - Tmp dir root location: 
 /tmp
[2019-01-01 22:41:50,687] {bash_operator.py:87} INFO - Temporary script location: /tmp/airflowtmplnxnq0d_/runme_3jicl23rs
[2019-01-01 22:41:50,687] {bash_operator.py:97} INFO - Running command: echo "my_dag__runme_3__20181231" && sleep 300
[2019-01-01 22:41:50,698] {bash_operator.py:106} INFO - Output:
[2019-01-01 22:41:50,699] {bash_operator.py:110} INFO - my_dag__runme_3__20181231
[2019-01-01 22:42:14,680] {models.py:1636} ERROR - Received SIGTERM. Terminating subprocesses.
[2019-01-01 22:42:14,681] {bash_operator.py:124} INFO - Sending SIGTERM signal to bash process group
[2019-01-01 22:42:14,706] {models.py:1760} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models.py", line 1659, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 108, in execute
    for line in iter(sp.stdout.readline, b''):
  File "/usr/local/lib/python3.7/site-packages/airflow/models.py", line 1638, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2019-01-01 22:42:14,829] {models.py:1791} INFO - Marking task as FAILED.
```

**Comment by villasv** [comment]
Apparently, though, Airflow will correctly retry those tasks. According to folks at the Airflow Developers channel, task-acks-late is already used (or something similar) so tasks that fail because of a `SIGTERM` should be already protected.

**Comment by villasv** [comment]
Confirmed, yes. Airflow mostly gets it right. Mostly because the DAG state still stays as `FAILED` after the retry, but that's Airflow business.

So this is not a bug, not even an issue. #36 is a problem, but this one is intended behavior.
